name: deploy-prod
on:
  workflow_dispatch:
jobs:
  deploy-to-k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.6.3

      - name: Set k8s context
        uses: Azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Set up Tailscale VPN
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_KEY }}

      - name: Deploy to Kubernetes with Helm
        run: |
          helm upgrade --install \
            --set appImage.tag=${{ github.sha }} \
            --set dbImage.tag=${{ github.sha }} \
            morjoff-com-website helm --values helm/values.yaml
